bookmarks/blog/urls.py
from django.urls import path
from .views import HomeView,PostDetailView,CreatePostView,PostEditView,PostDeleteView

urlpatterns = [
    path('',HomeView.as_view(),name="home"),
    path('article/<int:pk>/',PostDetailView.as_view(),name="post-detail"),
    path('post/new/',CreatePostView.as_view(),name="post-new"),
    path('article/<int:pk>/edit/',PostEditView.as_view(),name="post-edit"),
    path('article/<int:pk>/remove/',PostDeleteView.as_view(),name='post-delete'),
]

bookmarks/bookmarks/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Post(models.Model):
	title = models.CharField(max_length=255)
	author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
	photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
	body = models.TextField()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('post-detail',args=(str(self.id)))

	

bookmarks/blog/forms.py
from django import forms

bookmarks/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from .models import Post
from django.urls import reverse_lazy 
# Create your views here.

class HomeView(ListView):
	model = Post
	template_name = 'home.html'
	context_object_name = 'posts'

class PostDetailView(DetailView):
	model = Post
	template_name = 'post_detail.html'

class CreatePostView(CreateView):
	model = Post
	template_name = 'new_post.html'
	fields = '__all__'

class PostEditView(UpdateView):
	model = Post
	template_name = 'edit_post.html'
	fields = ['title','body','photo']

class PostDeleteView(DeleteView):
	model = Post
	template_name = 'delete_post.html'
	success_url = reverse_lazy('home')

bookmarks/blog/templates/delete_post.html
{% extends 'base.html'%}

{% block title %}
	Delete {{post.title}}
{% endblock%}

{% block content %}
	<div class="new_post">
		<form method="POST">
			{% csrf_token%}
			<h2>Czy napewno chcesz usunąć wpis ? </h2>
			<p>Delete : {{post.title}}</p>
			<div><button>Delete</button></div>
		</form>
		
	</div>

{% endblock %}

bookmarks/blog/templates/edit_post.html
{% extends 'base.html'%}

{% block title %}
	Edit Post 
{% endblock%}

{% block content %}
	<div class="new_post">
		<form method="POST" >
			{% csrf_token%}
			{{form.as_p}}
			   <p><input type="submit" value="Zapisz zmiany"></p>
		</form>
	</div>

{% endblock %}

bookmarks/blog/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if request.user.is_authenticated %}
<h2 class="post_title"><a href="./post/new/">Dodaj nowy</a>
{% for post in posts %}
		<div class="post_entry">
			<h2 class="post_title">
				{% if post.author|stringformat:"s" == request.user.username %}
				<a href="{% url 'post-detail' post.pk %}">{{post.title}}</a><br>
				    {% else %}
				{{post.title}}
				{% endif %}
				 {% if post.photo %}
    				<img src="{{ post.photo.url }}"  height="200" alt="obrazek"/>
    			 {% endif %}
			</h2>
			<p class="post_content">{{post.body}}<br>
			<b><span style="color: blue;">Napisał: {{post.author}}</span> <b>
			</p>

		</div>
	{%endfor%}

    {% else %}
      <a href="{% url "login" %}"><img src="{% static "img/login.png" %}" width="150" height="150 "></img></a>
	  <a href="{% url "register" %}"><img style="margin-bottom:35px; margin-left:200px;" src="{% static "img/register.png" %}" width="160" height="80"></img></a>

    {% endif %}


{% endblock %}

bookmarks/blog/templates/new_post.html
{% extends 'base.html'%}

{% block title %}
	Add New Post
{% endblock%}

{% block content %}
	<div class="new_post">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token%}
			<p>
				<label for="id_title">Tytuł:</label>
				<input type="text" name="title" maxlength="255" required id="id_title">
			</p>
			<p><input type="hidden" name="author" value="{{request.user.id}}"></p>
			<p><label for="id_photo">Photo:</label> <input type="file" name="photo" accept="image/*" id="id_photo"></p>
<p><label for="id_body">Wpis:</label> <textarea name="body" cols="40" rows="10" required id="id_body">
</textarea></p>
			<div><button>Zapisz</button></div>

		</form>
		
	</div>

{% endblock %}

bookmarks/blog/templates/post_detail.html
{% extends 'base.html' %}

{% block title %}
	{{post.title}}
{% endblock%}

{%block content %}
	
	<div class="post_details">
		<div class="post_info">
			<h1>{{post.title}}</h1>

			<div class="post_detail_meta">
				 {% if post.photo %}
    				<img class="image-detail"  src="{{ post.photo.url }}"   alt="obrazek"/>
    {% endif %}

			<p>Author: {{post.author}} | <a href="{% url 'post-edit' post.pk %}"> Edytuj Post </a> | <a href="{% url 'post-delete' post.pk%}"> Usuń post</a></p>

		</div>
		</div>
		
		<p class="post_detail_content">
			{{post.body}}

		</p>
<br><a href="/">Wstecz</a>
	</div>

{% endblock%}